[tool.ruff]
line-length = 100

[tool.ruff.lint]
preview = true
select = ['D1', 'D201', 'D3', 'F', 'E', 'W', 'N', 'B', 'I', 'UP', 'ANN', 'ARG', 'R', 'PERF', 'DOC']
ignore = ['D300', 'DOC201', 'DOC501']

[tool.ruff.format]
quote-style = "single"
skip-magic-trailing-comma = true